sudo: false
language: php
php:
  - 5.5
  - 5.6

# Set environment variables
node_js:
  - "0.10"
services:
  - mysql
env:
  matrix:
  - APP_ENV=testing DB_HOST=localhost DB_DATABASE=madison_testing DB_USERNAME=root
  global:
  - secure: XPSHwPKz6T6gKRYD8gmBZI1TRU79VpE/puIdIzno3mcVfR9Mt0jR39r759EGOGX94rNo2vjoBlOHLvECSYKl6kn1gjuWQDq8LkOD2QGKO+KmE8GDaED4DFds6EvtoHm/pkFpVBsvjGucU6PEZo4ghxhQAGpuX112V5mj1qmf7g0=
  - secure: eRHMypmB5JXiQXwa++FHjbNPg1LnLxJ97HTt/tcL4hrb9KTAioIg4vvOM07PaekLVkZnTtUnOUDDaOlkhSUzjUKaU+fnw4GcUvXTzj73efBSfkoSvWgkquiVCLV+8PJuYkske93ZcR5s91+4oPITQZ4IQVmviaUz3XdLFOgUUFk=
  - secure: ZD6cJNRU7u8kR6n6ffWFe2wNQydPh/aPaSUuVJVTqjGD/rZwQN6UK+v9ZbRCfZidMmzIkQF91mBeNWMiTr78mhNWt6lKAjYrZUdeQ1dEm+eDeemrZaG35xVMNcNyX7e2FL8XWv0CZ2dMNci2M2HEY/Zj5GElwzKEdwzMbxj3vfQ=
  - secure: FSuX4akl3gFy6WyCUotffJD07Jlz8C/WEZHpRr3bGmPR7+wIOOfcnhfhQ303ZDgxY+sCdOE6d47suWGSPBkJ0TrqImWhXYD/ChZmL6cOXe8OKkC5r4gE29tkG9ZrSD9WBV/bqgQn9kwEmTe6dTYDP8NJxSqv4PchoJ3IcGSFf0g=
addons:
  sauce_connect: true
  hosts:
   - madison
before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B -n 1 $TRAVIS_COMMIT)\""
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - grunt install
  - mysql -e 'create database madison_testing;'

# Commands you want to run that will verify your build.
script:
  #- grunt karma
  #- grunt test_firefox
  - grunt test_chrome
  #- grunt test_ie
  #- grunt test_safari
  #- phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true
notifications:
  on_success: never
  on_failure: always
